https://forum.turkmmo.com/konu/3938195-ikarus-v2-minimap-mark/
https://forum.turkmmo.com/konu/3905638-mini-map-yakinlastirma-duzenlemesi/
https://forum.turkmmo.com/konu/3926123-metin2de-canavar-ve-npc-isim-yuksekligi-hatasi-fix/
https://metin2.dev/topic/34299-c-gf-__loadatlasmarkinfo-whitemark-pixel-shift-fix/
https://metin2.dev/topic/33967-fix-questbuttons-out-of-questwindow-when-multiple-images-are-present/
https://metin2.dev/topic/16814-fix-for-the-refresh-of-the-skill-cooldown/
https://metin2.dev/topic/32961-fix-hitting-from-the-top-of-the-horse/
https://metin2.dev/topic/32247-fix-overin-tooltip-with-another-slot-behind/
https://metin2.dev/topic/29344-leadership-skill-description-bonus-values-display-fix/
https://forum.turkmmo.com/konu/3937667-system-monitoring-cpu-gpu-ram-fps/
https://forum.turkmmo.com/konu/3732417-ek-envanter-sistemi-k-envanteri/
